dataset: "LJSpeech"

path:
  df_path: "/home/heiscold/fastspeech2/inputs/csvs/ljs_with_arpa_tg.csv"
  corpus_path: "/home/heiscold/Data/LibriTTS/train-clean-360" 
  lexicon_path: "/home/heiscold/fastspeech2/lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data/LibriTTS" # in_dir # useless
  preprocessed_path: "/home/heiscold/fastspeech2/inputs/preprocessed/ljs/t_01" # "./preprocessed_data/LibriTTS" # out

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"] # ["english_cleaners"] # ["transliteration_cleaners"]
    language: "en_ljs"
  audio:
    denoiser: "False" # "non-stationary-noise-reduction"
    prop_decrease: 0.0                ## Denoiser's
    thresh_n_mult_nonstationary: 2    ## Denoiser's
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80  
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
